/*CIS 430 - LAB ASSIGNMENT 1
* NAME: Victor Ipinmoroti
* ID: 2681928
* OBJECTIVE: Creating a Table
*/
--TABLE 1
CREATE TABLE EMPLOYEE(
		FNAME VARCHAR(25) NOT NULL,
		MINIT CHAR,
		LNAME VARCHAR(25) NOT NULL,
		SSN   CHAR(9) NOT NULL, 
		BDATE DATE,
		ADRESSS VARCHAR(50) NOT NULL,
		SEX CHAR NOT NULL,
		SALARY DECIMAL(18,2),
		SUPERSSN CHAR(9),
		DNO  INT NOT NULL
);
